package com.sebangsa.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ADDRESS".
 */
public class Address {

    private Long id;
    /** Not-null value. */
    private String address;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    public Address(Long id, String address) {
        this.id = id;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
