package com.sebangsa.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sebangsa.greendao.db.Customer;
import com.sebangsa.greendao.db.Address;
import com.sebangsa.greendao.db.Order;
import com.sebangsa.greendao.db.Item;
import com.sebangsa.greendao.db.OrderItem;

import com.sebangsa.greendao.db.CustomerDao;
import com.sebangsa.greendao.db.AddressDao;
import com.sebangsa.greendao.db.OrderDao;
import com.sebangsa.greendao.db.ItemDao;
import com.sebangsa.greendao.db.OrderItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customerDaoConfig;
    private final DaoConfig addressDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig orderItemDaoConfig;

    private final CustomerDao customerDao;
    private final AddressDao addressDao;
    private final OrderDao orderDao;
    private final ItemDao itemDao;
    private final OrderItemDao orderItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        orderItemDaoConfig = daoConfigMap.get(OrderItemDao.class).clone();
        orderItemDaoConfig.initIdentityScope(type);

        customerDao = new CustomerDao(customerDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        orderItemDao = new OrderItemDao(orderItemDaoConfig, this);

        registerDao(Customer.class, customerDao);
        registerDao(Address.class, addressDao);
        registerDao(Order.class, orderDao);
        registerDao(Item.class, itemDao);
        registerDao(OrderItem.class, orderItemDao);
    }
    
    public void clear() {
        customerDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        orderItemDaoConfig.getIdentityScope().clear();
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public OrderItemDao getOrderItemDao() {
        return orderItemDao;
    }

}
